PREFIX ot:<http://wallscope.co.uk/resource/olympics/team/>
PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX dbp:<http://dbpedia.org/property/>
PREFIX oa:<http://wallscope.co.uk/resource/olympics/athlete/>
PREFIX oc:<http://wallscope.co.uk/resource/olympics/city/>
PREFIX o:<http://wallscope.co.uk/resource/olympics/>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX skos:<http://www.w3.org/2004/02/skos/core#>

CONSTRUCT {
  ?URI a foaf:Person.
}
FROM <file:olympics_snippet.csv>
WHERE {
  BIND (URI(CONCAT('http://wallscope.co.uk/resource/olympics/athlete/', ?ID)) AS ?URI)
}